{
  "success": true,
  "message": "",
  "data":
  {
    "inputCharset": "1",
    "pickupUrl": "http://localhost:8090/admin/stock?tab=order",
    "receiveUrl": "http://111.230.170.36/tauto/allInPayWeb/resultPayWeb",
    "version": "v1.0",
    "language": "1",
    "signType": "0",
    "merchantId": "",
    "payerName": "订单的卖方",
    "payerEmail": null,
    "payerTelephone": null,
    "orderNo": "DC2017112020422925Sx",
    "orderAmount": "300000",
    "orderCurrency": "0",
    "orderDatetime": "20171120084229",
    "orderExpireDatetime": "9999",
    "productName": "一汽-大众奥迪 奥迪A3 2010 1.6 手动高配",
    "productPrice": "2479",
    "productNum": "121",
    "productId": null,
    "productDesc": null,
    "ext1": null,
    "ext2": null,
    "extTL": null,
    "payType": "0",
    "issuerId": null,
    "pan": null,
    "tradeNature": null,
    "signMsg": "D9973DBCAEBCF437D2148B01FDFEABC1",
    "customsExt": null,
    "payerIDCard": null,
    "pid": null
  },
  "resultCode": 200
}